### ISSUE TITLE
'GlobalConvBlock' object has no attribute 'weight'

### ISSUE THREAD

**Issue by vivek239** [Never-less/SegAN#1]
I am trying to implement your code for medical image segmentation problem. When I tried to run the train.py file it always giving me an error 'GlobalConvBlock' object has no attribute 'weight'.
Please try to resolve this issue.

**Comment by YuanXue1993** [comment]
Will try this tomorrow. Could you give more details about the error?

**Comment by vivek239** [comment]
when I fixed this above error model works , but during 1st epoch model freezed. Means not going to next epoch. Please try to fix all these error.

**Comment by YuanXue1993** [comment]
I have fixed several bugs in train.py, now it's working well on my end. If you encounter out of memory error during the training, try to use a smaller batchsize. E.g., run with 
`CUDA_VISIBLE_DEVICES=0 python train.py --cuda --batchSize 25`

**Comment by John1231983** [comment]
@YuanXue1993 : What is purpose for using `GlobalConvBlock`? Thanks
