### ISSUE TITLE
i got an error in the dataloader_val , raising an exception 

### ISSUE THREAD

**Issue by NeoKun004** [Never-less/SegAN#9]
![files](https://user-images.githubusercontent.com/26217778/56424306-94fa4180-62a7-11e9-90a2-ba34ef455993.PNG)

**Comment by NeoKun004** [comment]
for some reason it's not reading the data, I m working with the ISIC-2017 data as recommended

**Comment by YuanXue1993** [comment]
It seems you are using a Windows machine, paths will be different in Windows and you need to modify the code accordingly.
